title: Dan Powell 
logo: /assets/img/me.jpg
description: Data-driven problem-solver with a proven track record in the biotech and e-commerce industries. Skilled in data mining, statistical modeling, and machine learning. Experienced in leading teams and managing large-scale analytical projects.
#show_downloads: true
theme: jekyll-theme-minimal
